export interface BathPlaceInterface {
  OVR_dataEDITFRILUFTSLIV_MOTION_PUNKT_1OBJECTID: number;
  OVR_dataEDITFRILUFTSLIV_MOTION_PUNKT_1NAMN: string;
  OVR_dataEDITFRILUFTSLIV_MOTION_PUNKT_1HUVUDMAN: string;
  OVR_dataEDITFRILUFTSLIV_MOTION_PUNKT_1TYP: number;
  OVR_dataEDITFRILUFTSLIV_MOTION_PUNKT_1OVRIGT: string;
  OVR_dataEDITBADPLATSEROBJECTID: number;
  OVR_dataEDITBADPLATSERID: number;
  OVR_dataEDITBADPLATSERBADPL_NAMN: string;
  OVR_dataEDITBADPLATSERHUVUDMAN: string;
  OVR_dataEDITBADPLATSERÄGARE: string;
  OVR_dataEDITBADPLATSERDRIFT: string;
  OVR_dataEDITBADPLATSERÖVRIGT: string;
  OVR_dataEDITBADPLATSERVATTENPROV: string;
  OVR_dataEDITBADPLATSERKOD_SSI: number;
  x: number
  y: number
}

